### PR TITLE
linux py36 builds not available: bump build to trigger rebuild

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by ericdill** [comment]
cc @parente

**Comment by ericdill** [comment]
@CJ-Wright i'm getting a weird appveyor build error. Have you seen this before?

```
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::jupyter_core-4.4.0-py_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda35-x64\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.
CondaError: Cannot link a source that does not exist. C:\Miniconda35-x64\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
```

**Comment by CJ-Wright** [comment]
That is very weird, I haven't seen that before. This may be relevant https://github.com/conda/conda/issues/6057

**Comment by ericdill** [comment]
@CJ-Wright thanks for the link. Seems like kale's comment might be the culprit here since jupyter-core is a noarch package

> It's clear to me that this is an issue with entry point creation for python noarch packages on windows. Looking into it.

Do we have any known workaround for this?

**Comment by ericdill** [comment]
edit: since jupyter-core is a noarch package with entry points [link](https://github.com/conda-forge/jupyter_core-feedstock/blob/master/recipe/meta.yaml#L15-L19)

**Comment by CJ-Wright** [comment]
@conda-forge-admin, please rerender

**Comment by ericdill** [comment]
good call @CJ-Wright

**Comment by CJ-Wright** [comment]
@ericdill I think you're ready to go

**Comment by ericdill** [comment]
thanks for the help @CJ-Wright

**Comment by CJ-Wright** [comment]
of course

**Pull request merged**
